version: 2
updates:
  - package-ecosystem: bundler
    directory: /
    schedule:
      interval: daily
    assignees:
      - daveio
  - package-ecosystem: cargo
    directory: /
    schedule:
      interval: daily
    assignees:
      - daveio
  - package-ecosystem: docker
    directory: /
    schedule:
      interval: daily
    assignees:
      - daveio
  - package-ecosystem: github-actions
    directory: /
    schedule:
      interval: daily
    assignees:
      - daveio
  - package-ecosystem: gomod
    directory: /
    schedule:
      interval: daily
    assignees:
      - daveio
  - package-ecosystem: npm
    directory: /
    schedule:
      interval: daily
    assignees:
      - daveio
  - package-ecosystem: pip
    directory: /
    schedule:
      interval: daily
    assignees:
      - daveio
