version: 2
updates:
  - package-ecosystem: bun
    directory: /
    schedule:
      interval: daily
    open-pull-requests-limit: 100
    assignees:
      - daveio
  - package-ecosystem: pub
    directory: /
    schedule:
      interval: daily
    open-pull-requests-limit: 100
    assignees:
      - daveio
  - package-ecosystem: terraform
    directory: /
    schedule:
      interval: daily
    open-pull-requests-limit: 100
    assignees:
      - daveio
  - package-ecosystem: bundler
    directory: /
    schedule:
      interval: daily
    open-pull-requests-limit: 100
    assignees:
      - daveio
  - package-ecosystem: cargo
    directory: /
    schedule:
      interval: daily
    open-pull-requests-limit: 100
    assignees:
      - daveio
  - package-ecosystem: composer
    directory: /
    schedule:
      interval: daily
    open-pull-requests-limit: 100
    assignees:
      - daveio
  - package-ecosystem: docker
    directory: /
    schedule:
      interval: daily
    open-pull-requests-limit: 100
    assignees:
      - daveio
  - package-ecosystem: github-actions
    directory: /
    schedule:
      interval: daily
    open-pull-requests-limit: 100
    assignees:
      - daveio
  - package-ecosystem: gitsubmodule
    directory: /
    schedule:
      interval: daily
    open-pull-requests-limit: 100
    assignees:
      - daveio
  - package-ecosystem: gomod
    directory: /
    schedule:
      interval: daily
    open-pull-requests-limit: 100
    assignees:
      - daveio
  - package-ecosystem: gradle
    directory: /
    schedule:
      interval: daily
    open-pull-requests-limit: 100
    assignees:
      - daveio
  - package-ecosystem: maven
    directory: /
    schedule:
      interval: daily
    open-pull-requests-limit: 100
    assignees:
      - daveio
  - package-ecosystem: mix
    directory: /
    schedule:
      interval: daily
    open-pull-requests-limit: 100
    assignees:
      - daveio
  - package-ecosystem: npm
    directory: /
    schedule:
      interval: daily
    open-pull-requests-limit: 100
    assignees:
      - daveio
  - package-ecosystem: nuget
    directory: /
    schedule:
      interval: daily
    open-pull-requests-limit: 100
    assignees:
      - daveio
  - package-ecosystem: pip
    directory: /
    schedule:
      interval: daily
    open-pull-requests-limit: 100
    assignees:
      - daveio
